---

- name: Check dkimproxy existance
  shell: ls /usr/local/bin/
  register: ls_dkimproxyout

- name: Ensure dkimproxy installed
  sudo: yes
  openbsd_pkg: name=dkimproxy-1.4.1p0 state=installed

- name: dkimproxy configuration
  copy: src=etc_dkimproxy_out.conf dest=/etc/dkimproxy_out.conf owner=root group=wheel mode=0644
  notify: restart dkimproxy

- name: dkimproxy sender map configuration
  copy: src=etc_dkim_sender_map dest=/etc/dkim_sender_map owner=root group=wheel mode=0644
  notify: restart dkimproxy

- name: add dkimproxy service to rc.conf.local
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='dkimproxy_out_enable="YES"'
    state=present
    insertafter=EOF
    create=True
  notify: restart dkimproxy
