- name: Install Dovecot
  openbsd_pkg: name={{ item }} state=installed
  with_items:
    - dovecot
    - dovecot-pigeonhole

- name: Ensure dovecot resource limits
  sudo: yes
  lineinfile: "dest=/etc/login.conf backup=yes line='dovecot: :openfiles-cur=512: :openfiles-max=2048: :tc=daemon:' regexp='^dovecot: :openfiles-cur=512: :openfiles-max=2048: :tc=daemon:$' state=present create=True insertafter=EOF"
  notify:
      - Rerun loginconf database

- name: Dovecot config
  copy: src=etc_dovecot_dovecot.conf dest=/etc/dovecot/dovecot.conf

- name: Copy additional Dovecot configuration files in place
  copy: src=etc_dovecot_conf.d_{{ item }} dest=/etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-auth.conf
    - 10-mail.conf
    - 10-master.conf
    - 10-ssl.conf
    - 20-imap.conf
    - 20-lmtp.conf
    - 90-plugin.conf
  notify: restart dovecot


#- name: Template 15-lda.conf
#  template: src=etc_dovecot_conf.d_15-lda.conf.j2 dest=/etc/dovecot/conf.d/15-lda.conf
#  notify: restart dovecot
#
#- name: Template dovecot-sql.conf.ext
#  template: src=etc_dovecot_dovecot-sql.conf.ext.j2 dest=/etc/dovecot/dovecot-sql.conf.ext
#  notify: restart dovecot
#
#- name: Ensure correct permissions on Dovecot config directory
#  file: state=directory path=/etc/dovecot
#          group=dovecot owner=vmail mode=770 recurse=yes
#  notify: restart dovecot
#
#- name: Set firewall rules for dovecot
#  ufw: rule=allow port={{ item }} proto=tcp
#  with_items:
#    - imaps
#    - pop3s
