- include: opensmtpd.yml tags=opensmtpd
- include: spampd.yml tags=spampd
- include: dovecot.yml tags=dovecot
- include: dkimproxy.yml tags=dkimproxy

#- include: opendkim.yml tags=opendkim
#- include: dspam.yml tags=dspam
#- include: solr.yml tags=solr
#- include: checkrbl.yml tags=checkrbl
#- include: z-push.yml tags=zpush
#- include: autoconfig.yml tags=autoconfig
