---

- name: Install spampd
  openbsd_pkg: name=spampd state=installed

- name: add spampd service to rc.conf.local
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='spampd_flags="--tagall --relayport=10026"'
    regexp='^spampd_flags="--tagall --relayport=10026"$'
    state=present
    insertafter=EOF
    create=True
  notify: restart spampd

- name: enable daily cron for updating spam db
  sudo: yes
  lineinfile:
    dest=/var/cron/tabs/root
    backup=yes
    line='20      6       *       *       *       /usr/local/bin/sa-update && /etc/rc.d/spampd restart'
    regexp='^20      6       *       *       *       /usr/local/bin/sa-update && /etc/rc.d/spampd restart$'
    state=present
    insertafter=EOF
    create=True
