- name: Install roundcube
  openbsd_pkg: name={{ item }} state=installed
  with_items:
      - roundcubemail

- postgresql_db: name={{ webmail_db_database }}
                 encoding='UTF-8'
                 template='template0'
  notify: setup roundcube database

- postgresql_user: db={{ webmail_db_database }}
                   name={{ webmail_db_username }}
                   password={{ webmail_db_password }}
                   priv=ALL
  notify: setup roundcube database

- name: roundcube configuration
  template: src=roundcube_config.inc.php dest=/var/www/roundcubemail/config/config.inc.php owner=root group=daemon mode=0644
  notify: restart php-fpm

- name: roundcube nginx configuration
  copy: src=etc_nginx_roundcube.conf dest=/etc/nginx/sites-available/roundcube.conf owner=root group=wheel mode=0644

- name: enable roundcube nginx
  file: src=/etc/nginx/sites-available/roundcube.conf dest=/etc/nginx/sites-enabled/roundcube.conf owner=root group=wheel state=link
  notify: reload nginx

# - name: Download carddav plugin release
# get_url:
# url=https://github.com/blind-coder/rcmcarddav/archive/carddav_{{ carddav_version }}.tar.gz
# dest=/root/carddav_{{ carddav_version }}.tar.gz
# 
# - name: Decompress carddav plugin source
# command: tar xzf carddav_{{ carddav_version }}.tar.gz chdir=/root creates=/root/rcmcarddav-carddav_{{ carddav_version }}
# 
# - name: Move carddav plugin files to /usr/share/roundcube/plugins/carddav
# command: mv rcmcarddav-carddav_{{ carddav_version }} /usr/share/roundcube/plugins/carddav chdir=/root creates=/usr/share/roundcube/plugins/carddav
# 
# - name: Download Google Authenticator roundcube plugin
# git: repo=https://github.com/alexandregz/twofactor_gauthenticator.git
# dest=/usr/share/roundcube/plugins/twofactor_gauthenticator
# accept_hostkey=yes
# 
# - name: Link plugins into /var/lib/roundcube/plugins
# file: state=link src=/usr/share/roundcube/plugins/{{ item }} dest=/var/lib/roundcube/plugins/{{ item }} force=yes
# with_items:
# - carddav
# - twofactor_gauthenticator
# 
# - name: Rename existing Apache roundcube virtualhost
# command: mv /etc/apache2/sites-available/roundcube /etc/apache2/sites-available/roundcube.conf removes=/etc/apache2/sites-available/roundcube
# 
# - name: Remove old sites-enabled/roundcube symlink (new one will be created by a2ensite)
# command: rm /etc/apache2/sites-enabled/roundcube removes=/etc/apache2/sites-enabled/roundcube
# 
# - name: Configure the Apache HTTP server for roundcube
# template: src=etc_apache2_sites-available_roundcube.j2 dest=/etc/apache2/sites-available/roundcube.conf group=root owner=root force=yes
# 
# - name: Configure roundcube
# copy: src={{ item.src }} dest={{ item.dest }} group=www-data owner=root mode=640 force=yes
# with_items:
# - { src: 'etc_roundcube_global.sieve',                                          dest: '/etc/roundcube/global.sieve' }
# - { src: 'etc_roundcube_main.inc.php',                                          dest: '/etc/roundcube/main.inc.php' }
# - { src: 'usr_share_roundcube_plugins_carddav_config.inc.php',                  dest: '/usr/share/roundcube/plugins/carddav/config.inc.php' }
# - { src: 'usr_share_roundcube_plugins_managesieve_config.inc.php',              dest: '/usr/share/roundcube/plugins/managesieve/config.inc.php' }
# - { src: 'usr_share_roundcube_plugins_twofactor_gauthenticator_config.inc.php', dest: '/usr/share/roundcube/plugins/twofactor_gauthenticator/config.inc.php' }
# 
# - name: Enable roundcube site
# command: a2ensite roundcube.conf creates=/etc/apache2/sites-enabled/roundcube.conf
# notify: restart apache
