---
# Defines tasks applicable across all machines in the infrastructure.

- name: Install necessities and nice-to-haves
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - git
    - iftop
    - mosh
    - screen-4.0.3p4-shm
    - vim--no_x11
    - zsh

- name: Disable X11 for ports
  sudo: yes
  copy: src=etc_make.conf dest=/etc/make.conf owner=root group=wheel mode=0644

- include: ntp.yml tags=ntp
- include: ssl.yml tags=ssl

#- include: encfs.yml tags=encfs
#- include: users.yml tags=users
#- include: ufw.yml tags=ufw
#- include: security.yml tags=security
#- include: google_auth.yml tags=google_auth
#  when: ansible_distribution_release != 'trusty'
#- include: google_auth_mod.yml tags=google_auth
#  when: ansible_distribution_release == 'trusty'
