---
# Defines tasks applicable across all machines in the infrastructure.

- name: Install necessities and nice-to-haves
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - git
    - iftop
    - mosh
    - screen-4.0.3p4-shm
    - vim--no_x11
    - zsh
    - lsof

- name: Disable X11 for ports
  sudo: yes
  copy: src=etc_make.conf dest=/etc/make.conf owner=root group=wheel mode=0644

- name: set nginx startup flags
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='nginx_flags=""'
    regexp='^nginx_flags=""$'
    state=present
    insertafter=EOF
    create=True

- name: ensure nginx directories
  file: state=directory path=/etc/nginx/{{ item }}
  with_items:
    - sites-available
    - sites-enabled

- name: default nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=wheel mode=0644
  notify:
      - restart nginx

- name: Ensure nginx resource limits
  sudo: yes
  lineinfile: "dest=/etc/login.conf backup=yes line='nginx: :openfiles-cur=512: :openfiles-max=2048: :tc=daemon:' regexp='^nginx: :openfiles-cur=512: :openfiles-max=2048: :tc=daemon:$' state=present create=True insertafter=EOF"
  notify:
      - Rerun loginconf database
      - restart nginx

- name: Install php
  openbsd_pkg: name={{ item }} state=installed
  with_items:
      - php-{{ php_version }}p0
      - php-bz2-{{ php_version }}
      - php-gd-{{ php_version }}
      - php-gmp-{{ php_version }}
      - php-mcrypt-{{ php_version }}
      - php-pgsql-{{ php_version }}
      - php-zip-{{ php_version }}
      - php-fpm-{{ php_version }}
      - php-pdo_pgsql-{{ php_version }}
      - php-pspell-{{ php_version }}

- name: upload php fpm config
  copy: src=etc_php-fpm.conf dest=/etc/php-fpm.conf owner=root group=wheel mode=0644

- name: add php_fpm service to rc.conf.local
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='php_fpm_enable="YES"'
    regexp='^php_fpm_enable="YES"$'
    state=present
    insertafter=EOF
    create=True
  notify: restart dkimproxy

- include: ntp.yml tags=ntp
- include: ssl.yml tags=ssl

#- include: encfs.yml tags=encfs
#- include: users.yml tags=users
#- include: ufw.yml tags=ufw
#- include: security.yml tags=security
#- include: google_auth.yml tags=google_auth
#  when: ansible_distribution_release != 'trusty'
#- include: google_auth_mod.yml tags=google_auth
#  when: ansible_distribution_release == 'trusty'
