---
# Defines tasks applicable across all machines in the infrastructure.

- name: Install necessities and nice-to-haves
  openbsd_pkg: name={{ item }} state=present
  with_items:
    - git
    - iftop
    - mosh
    - screen-4.0.3p4-shm
    - vim--no_x11
    - zsh
    - lsof
    - mutt-1.5.23p9v0-compressed-sasl-sidebar-slang

- name: Disable X11 for ports
  sudo: yes
  copy: src=etc_make.conf dest=/etc/make.conf owner=root group=wheel mode=0644

- name: update rc.conf.local pkg_scripts
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='pkg_scripts="{{ pkg_scripts }}"'
    regexp='^pkg_scripts=".*"$'
    state=present
    insertafter=EOF
    create=True


- include: ntp.yml tags=ntp
- include: ssl.yml tags=ssl

#- include: encfs.yml tags=encfs
#- include: users.yml tags=users
#- include: ufw.yml tags=ufw
#- include: security.yml tags=security
#- include: google_auth.yml tags=google_auth
#  when: ansible_distribution_release != 'trusty'
#- include: google_auth_mod.yml tags=google_auth
#  when: ansible_distribution_release == 'trusty'
