---

- name: Create SSL certs directory
  file: state=directory path=/etc/ssl/certs

- name: Create SSL private directory
  file: state=directory path=/etc/ssl/private

- name: Copy SSL private keys
  copy: src={{ item }} dest=/etc/ssl/private/{{ item }} group=wheel owner=root mode=0600
  with_items:
    - wildcard_private.key
    - dkim_private.key

- name: Copy SSL public certificates
  copy: src={{ item }} dest=/etc/ssl/certs/{{ item }} group=wheel owner=root mode=644
  with_items:
    - wildcard_public_cert.crt
    - dkim_public.crt

- name: Copy CA combined certificate into place
  copy: src=wildcard_ca.pem dest=/etc/ssl/certs/wildcard_ca.pem group=wheel owner=root mode=644

- name: Create a combined version of the public cert with intermediate and root CAs
  shell: cat /etc/ssl/certs/wildcard_public_cert.crt /etc/ssl/certs/wildcard_ca.pem >
    /etc/ssl/certs/wildcard_combined.pem creates=/etc/ssl/certs/wildcard_combined.pem

- name: Set permissions on combined public cert
  file: name=/etc/ssl/certs/wildcard_combined.pem mode=644
