- name: restart dovecot
  service: name=dovecot state=restarted

- name: restart opendkim
  service: name=opendkim state=restarted

- name: restart solr
  service: name=tomcat6 state=restarted

- name: restart smtpd
  service: name=smtpd state=restarted

- name: run newaliases
  sudo: yes
  action: shell newaliases

- name: Rerun loginconf database
  sudo: yes
  action: shell cap_mkdb /etc/login.conf

- name: restart spampd
  service: name=spampd state=restarted

- name: restart dkimproxy
  service: name=dkimproxy_out state=restarted
