---

- name: Install php
  openbsd_pkg: name={{ item }} state=installed
  with_items:
      - php-{{ php_version }}p0
      - php-bz2-{{ php_version }}
      - php-gd-{{ php_version }}
      - php-gmp-{{ php_version }}
      - php-mcrypt-{{ php_version }}
      - php-pgsql-{{ php_version }}
      - php-zip-{{ php_version }}
      - php-fpm-{{ php_version }}
      - php-pdo_pgsql-{{ php_version }}
      - php-pspell-{{ php_version }}

- name: upload php fpm config
  copy: src=etc_php-fpm.conf dest=/etc/php-fpm.conf owner=root group=wheel mode=0644

- name: add php_fpm service to rc.conf.local
  sudo: yes
  lineinfile:
    dest=/etc/rc.conf.local
    backup=yes
    line='php_fpm_enable="YES"'
    regexp='^php_fpm_enable="YES"$'
    state=present
    insertafter=EOF
    create=True
  notify: restart php_fpm
