
- name: Install php5
  apt: pkg={{ item }} state=installed
  with_items:
    - php5-cli
    - php5-fpm
    - php5-curl
    - php5-gd
    - php5-gmp
    - php5-intl
    - php5-mcrypt
    - php5-pgsql
    - php5-pspell
    - php5-xmlrpc
