---
# Installs the ownCloud personal cloud software

- name: Install ownloud
  openbsd_pkg: name=owncloud state=present

- name: Create database user for ownCloud
  postgresql_user: >
      login_host=localhost
      login_user={{ db_admin_username }}
      login_password="{{ db_admin_password }}"
      name={{ owncloud_db_username }}
      password="{{ owncloud_db_password }}"
      state=present

- name: Create database for ownCloud
  postgresql_db: >
      login_host=localhost
      login_user={{ db_admin_username }}
      login_password="{{ db_admin_password }}"
      name={{ owncloud_db_database }}
      state=present
      owner={{ owncloud_db_username }}

# - name: Store ownCloud data securely
#   command: mv /var/www/owncloud/data /decrypted/owncloud-data creates=/decrypted/owncloud-data
# - file: src=/decrypted/owncloud-data dest=/var/www/owncloud/data owner=www-data group=www-data state=link

#- name: Install ownCloud cronjob
#  cron: name="ownCloud" user="www" minute="*/15" job="curl -o /dev/null 'http://cloud.{{ domain }}/owncloud/cron.php'"

- name: Install ownCloud nginx
  template: src=etc_nginx_owncloud.conf.j2 dest=/etc/nginx/sites-available/owncloud.conf owner=root group=wheel mode=0644

- name: enable ownCloud nginx
  file: src=/etc/nginx/sites-available/owncloud.conf dest=/etc/nginx/sites-enabled/owncloud.conf owner=root group=wheel state=link
  notify: reload nginx

- name: Install ownCloud config
  template: src=config.php.j2 dest=/var/www/owncloud/config/config.php owner=www group=www mode=0640
  notify: reload nginx
